[[ manager.prepend_keymap ]]
on="T"
run="plugin --sync hide-preview"
desc="Hide or show preview"

[[ manager.prepend_keymap ]]
on="|"
run="plugin --sync max-preview"
desc="Maximize or restore preview"
